[package]
name = "replit_db"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-storage = "0.3.0"
actix-storage-hashmap = "0.3.0"
actix-web = "4"
serde = { version = "1.0.152", features = ["derive"] }

